export const ROLE_ADMIN = 'ADMIN';
export const ROLE_ORGANIZER = 'ORGANIZER';
export const ROLE_PLAYER = 'PLAYER';

export const TOURNAMENT_STATUS = {
  DRAFT: 'DRAFT',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};
